page_description: Yair Silbermintz, web developer focused on building secure web applications in PHP, JS, HTML5, CSS3, and much more
name: Yair Silbermintz
profession: REST API & Web Application Developer
email: Yair@Silbermintz.com
phone_formatted: (818) 935-5659
phone_raw: 18189355659
